version: '3'
services:
  # Node.js application
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - network
    depends_on:
      - redis
    environment:
      PORT: 8000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BULL_WORKER_ATTEMPTS: 3

  # Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - network
    volumes:
      - redis-data:/data

networks:
  network:
    driver: bridge

volumes:
  redis-data:
